### PR TITLE
PdfInfo.php to retrieve information of pdf file

### PR DESCRIPTION
**Pull request by AikChun**
We need to find out about the number of pages and since we are already using pdftotext via php-xpdf, we'd like to add pdfinfo to it.

### CODE REVIEW

**Comment by leoqbc** [comment]
Hi guys I'm very interested in this feature, I'm using pdftotext and also need pdfinfo, are you still interested to merge this code? you guys want some help? @romainneutron @AikChun 

These are minor changes and I can help if you guys want it.

thanks

**Comment by AikChun** [comment]
Hi, sorry for the inactivity. I did this when I was just started coding and didn't know better. I made changes  @romainneutron requested and ran the code through php cs fixer. I'm still interested in merging this code. Let me know if there's any more errors I should fix.

**Comment by aztech-dev** [comment]
Thank you for submitting and updating your pull request. I've merged the changes and will push a new release.

**Comment by leoqbc** [comment]
Nice! thank you guys!

**Pull request merged**
